# --- !Ups

create table "PRODUCT" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "PRICE_CURRENCY" VARCHAR NOT NULL,
  "PRICE_AMOUNT" DECIMAL(13,2) NOT NULL);

insert into PRODUCT values (1, 'EUR', 42.00);
insert into PRODUCT values (2, 'USD', 100.00);

# --- !Downs

drop table "PRODUCT";

